### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by alpharosto**
Application description  of HealthAI's

### CODE REVIEW

**Comment by alpharosto** [comment]
I can add more description if allowed to merge pull request

**Comment by medmac01** [comment]
> I can add more description if allowed to merge pull request
> 

Thank you for your contribution 🙏, for now it's enough. We might add some other details as we continue to develop the app.

**Comment by alpharosto** [comment]
It will be helpful to open source community if you register this app for hacktoberfest too.

**Comment by medmac01** [comment]
> It will be helpful to open source community if you register this app for hacktoberfest too.

Great idea! Thinking about it..

**Pull request merged**
